# Generated by Django 5.2.12 on 2026-03-06 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_remove_null_from_text_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.PositiveIntegerField()),
                ('label', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'frequencies',
                'ordering': ['days'],
            },
        ),
        migrations.AlterField(
            model_name='schedule',
            name='frequency_days',
            field=models.PositiveIntegerField(default=365),
        ),
        migrations.AddField(
            model_name='schedule',
            name='frequency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='maintenance.frequency'),
        ),
    ]
