# Generated by Django 5.2.12 on 2026-03-06 22:48

from django.db import migrations


def populate_frequencies(apps, schema_editor):
    """Create a Frequency for each unique (days, label) pair and assign to schedules."""
    Frequency = apps.get_model("maintenance", "Frequency")
    Schedule = apps.get_model("maintenance", "Schedule")

    for schedule in Schedule.objects.all():
        freq, _ = Frequency.objects.get_or_create(
            days=schedule.frequency_days,
            defaults={"label": schedule.frequency_label or ""},
        )
        schedule.frequency = freq
        schedule.save(update_fields=["frequency"])


def reverse_populate(apps, schema_editor):
    Schedule = apps.get_model("maintenance", "Schedule")
    for schedule in Schedule.objects.select_related("frequency").all():
        if schedule.frequency:
            schedule.frequency_days = schedule.frequency.days
            schedule.frequency_label = schedule.frequency.label
            schedule.save(update_fields=["frequency_days", "frequency_label"])


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_frequency_model'),
    ]

    operations = [
        migrations.RunPython(populate_frequencies, reverse_populate),
    ]
