# Generated by Django 5.2.12 on 2026-03-06 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_schedule_frequency_cleanup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='season_hint',
        ),
    ]
